apiVersion: v1
kind: Pod
metadata:
  name: sleep-priv
spec:
  hostPID: true
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      requests:
        cpu: 100m
    args:
    - sleep
    - "1000000"
    securityContext:
      privileged: true
      # allowPrivilegeEscalation: true
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
