apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
  volumes:
  - name: host-foot
    hostPath:
      path: /
      type: Directory
  containers:
  - name: what
    command:
    - "/bin/bash"
    - "-c"
    - "--"
    args:
    - "while true; do sleep 30; done;"
    image: ubuntu
    volumeMounts:
    - name: host-foot
      mountPath: /host-foot
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
      runAsUser: 0
